version: '3.7'

services:
  emissionsmap:
    volumes:
      - static:/static
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - src/.env
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "81:81"
    depends_on:
      - emissionsmap

volumes:
  static: